namespace DesktopNode.Host;

public sealed record DesktopNodeHostConfigMigrationSource(
    string Name,
    string Path,
    bool Owned,
    int? SchemaVersion,
    string? Version);

public sealed record DesktopNodeHostConfigMigrationDescriptor(
    string Operation,
    bool Ok,
    IReadOnlyList<DesktopNodeHostConfigMigrationSource> ConfigSources,
    string DataRoot,
    string ServiceName,
    string? MigrationPlanId,
    int? MigrationPlanVersion,
    bool MutationPlanned,
    bool MutationPerformed,
    bool ServiceStopped,
    string BackupRoot,
    string? ErrorCode,
    string? ErrorMessage,
    string? BackupPath = null,
    string? TempPath = null,
    int? SourceSchemaVersion = null,
    int? TargetSchemaVersion = null,
    bool RollbackAttempted = false,
    bool RollbackSucceeded = false,
    bool OriginalConfigRestored = false,
    bool PartialConfigPresent = false);

public sealed record DesktopNodeHostJobStoreMigrationDescriptor(
    string Operation,
    bool Ok,
    string JobStorePath,
    bool Owned,
    int? CurrentSchemaVersion,
    int JobCount,
    int QueueCount,
    string RuntimeWriter,
    string DataRoot,
    string ServiceName,
    string? MigrationPlanId,
    int? MigrationPlanVersion,
    bool MutationPlanned,
    bool MutationPerformed,
    bool ServiceStopped,
    string BackupRoot,
    string? ErrorCode,
    string? ErrorMessage,
    string? BackupPath = null,
    string? TempPath = null,
    int? SourceSchemaVersion = null,
    int? TargetSchemaVersion = null,
    bool RollbackAttempted = false,
    bool RollbackSucceeded = false,
    bool OriginalJobStoreRestored = false,
    bool PartialJobStorePresent = false,
    bool RecoveryRequired = false);

public sealed record DesktopNodeHostServiceTokenRotationDescriptor(
    string Operation,
    bool Ok,
    string DataRoot,
    string TokenPath,
    string BackupRoot,
    string? BackupPath,
    string AuditPath,
    string ServiceName,
    string ServiceTokenMutation,
    bool TokenValueObserved,
    bool NewTokenValueCreated,
    string ServiceReloadStatus,
    string OldTokenRejectionStatus,
    string TokenRotationAuditStatus,
    bool HostMutationPerformed,
    string PublicTrustedSigning,
    string ExternalStablePublication,
    string? OldTokenSha256,
    string NewTokenSha256,
    string BackupWriteStatus,
    string AtomicReplaceStatus);

public sealed record DesktopNodeHostEventLogHardeningDescriptor(
    string Operation,
    bool Ok,
    string ProviderRepairStatus,
    string EventWriteStatus,
    string VolumeGuardStatus,
    int? EventId,
    bool HostMutationPerformed,
    DesktopNodeWindowsEventLogVolumePolicySnapshot? VolumePolicy = null,
    string DefaultWriterStatus = "not-run",
    string ProviderRemoveStatus = "not-run",
    string FinalProviderStatus = "not-run",
    int? SchemaVersion = null,
    string PublicTrustedSigning = "not-claimed",
    string ExternalStablePublication = "not-claimed",
    int? TimeoutSeconds = null,
    string TimeoutGuardStatus = "not-run");

public sealed record DesktopNodeHostCredentialManagerProofDescriptor(
    string Operation,
    bool Ok,
    string ProofStatus,
    string Identity,
    string CredentialTarget,
    string CredentialWriteStatus,
    string CredentialReadStatus,
    string CredentialDeleteStatus,
    bool TokenValueObserved,
    bool NewTokenValueCreated,
    bool HostMutationPerformed,
    string PublicTrustedSigning,
    string ExternalStablePublication);

public sealed record DesktopNodeHostCredentialManagerTransitionDescriptor(
    string Operation,
    bool Ok,
    string Identity,
    string CredentialTarget,
    string DataRoot,
    string ProtectedTokenPath,
    string TransitionEvidencePath,
    string RollbackDiagnosticsPath,
    string ServiceName,
    string SystemProofStatus,
    string CredentialWriteStatus,
    string CredentialReadStatus,
    string CredentialDeleteStatus,
    string TokenSourceMigration,
    string ServiceReloadStatus,
    string OldSourceRejectionStatus,
    string RollbackDiagnosticsStatus,
    bool TokenValueObserved,
    bool NewTokenValueCreated,
    bool HostMutationPerformed,
    string PublicTrustedSigning,
    string ExternalStablePublication,
    string? PreviousBinaryPath,
    string? NextBinaryPath);
